// eslint-disable-next-line import/prefer-default-export
export const MAP = {
  DELETE_ITEM_LOCATION_TITLE: 'DELETE_ITEM_LOCATION_TITLE',
  DELETE_ITEM_LOCATION_EXPLANATION: 'DELETE_ITEM_LOCATION_EXPLANATION',
  DELETE_ITEM_LOCATION_BUTTON: 'DELETE_ITEM_LOCATION_BUTTON',
  DELETE_ITEM_BUTTON: 'DELETE_ITEM_BUTTON',
  DELETE_ITEM_TITLE: 'DELETE_ITEM_TITLE',
  DELETE_ITEM_EXPLANATION: 'DELETE_ITEM_EXPLANATION',
};
