// eslint-disable-next-line import/prefer-default-export
export const MAP = {
  DELETE_ITEM_LOCATION_TITLE: 'DELETE_ITEM_LOCATION_TITLE',
  DELETE_ITEM_LOCATION_EXPLANATION: 'DELETE_ITEM_LOCATION_EXPLANATION',
  DELETE_ITEM_LOCATION_BUTTON: 'DELETE_ITEM_LOCATION_BUTTON',
  DELETE_ITEM_BUTTON: 'DELETE_ITEM_BUTTON',
  DELETE_ITEM_TITLE: 'DELETE_ITEM_TITLE',
  DELETE_ITEM_EXPLANATION: 'DELETE_ITEM_EXPLANATION',
  GEOLOCATION_PICKER_PLACEHOLDER: 'GEOLOCATION_PICKER_PLACEHOLDER',
  GEOLOCATION_PICKER_NO_ADDRESS: 'GEOLOCATION_PICKER_NO_ADDRESS',
  GEOLOCATION_PICKER_TITLE: 'GEOLOCATION_PICKER_TITLE',
};
